### 회원가입
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "loginId": "test1",
  "password": "test1",
  "email": "ne2227@naver.com"
}

### 로그인
POST http://localhost:8080/user/signin
Content-Type: application/json

{
  "loginId": "test1",
  "password": "test2"
}